apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oc

commonLabels:
  app.kubernetes.io/instance: oc-backend
  app.kubernetes.io/name: oc-backend

resources:
- deployment.yaml
- ingress.yaml
- service.yaml
